EmcoCrud/EmcoCrud/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    #path('', views.index, name='index'),  # Redirige a la vista index
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]

EmcoCrud/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name="home"),
    path('update_info/<int:id>', views.update_info, name="update_info"),
    path('about', views.about, name="about"),
    path('upload_funtionary', views.upload_funtionary, name="upload_funtionary"),
    path('deleteData/<int:id>', views.deleteData, name="deleteData"),
    path('search', views.search, name="search"),    
    path('exportar-excel/', views.export_to_excel, name='export_to_excel'),
    path('products/', views.products, name='products'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EmcoCrud/core/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

# Create your models here.
from django.db import models

class Country(models.Model):
    nameCountry = models.CharField(max_length=200, verbose_name="Nombre del pais")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edicion")

    class Meta:
        verbose_name = "Pais"
        verbose_name_plural = "Paises"
        ordering = ["-created"]

    def __str__(self):
        return self.nameCountry

class State(models.Model):
    nameState = models.CharField(max_length=200, verbose_name="Nombre del estado")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edicion")
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Estados/Departamentos"
        verbose_name_plural = "Estado/Departamentos"
        ordering = ["-created"]

    def __str__(self):
        return self.nameState

class City(models.Model):
    nameCity = models.CharField(max_length=200, verbose_name="Nombre de la ciudad")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edicion")
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Ciudad"
        verbose_name_plural = "Ciudades"
        ordering = ["-created"]

    def __str__(self):
        return self.nameCity

class Headquarters(models.Model):
    nameHeadquarter = models.CharField(max_length=200, verbose_name="Nombre de la sede")
    Direction = models.CharField(max_length=200, verbose_name="Direccion de la sede")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edicion")
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Sede"
        verbose_name_plural = "Sedes"
        ordering = ["-created"]

    def __str__(self):
        return self.nameHeadquarter


class Speciality(models.Model):
    title = models.CharField(max_length=200, verbose_name="Especialidad")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edicion")

    class Meta:
        verbose_name = "Especialidad"
        verbose_name_plural = "Especialidades"
        ordering = ["-created"]

    def __str__(self):
        return self.title


# Funtionary model
class Funtionary(models.Model):
    identification = models.IntegerField()
    name = models.CharField(max_length=200, verbose_name="Nombre del funcionario")
    lastname = models.CharField(max_length=200, verbose_name="Apellido del funcionario")
    birthday=models.DateField(verbose_name='Fecha de nacimiento')
    telephone = models.CharField(max_length=10, verbose_name="Numero de celular")
    email = models.EmailField(max_length=200, verbose_name="Correo electronico")
    active = models.BooleanField(default=True, verbose_name="Activo")
    speciality = models.ForeignKey(Speciality, on_delete=models.CASCADE , max_length=200, verbose_name="Especialidad")
    #Curriculum docs
    curriculum = models.FileField(upload_to= 'curriculum/',verbose_name="Hoja de vida", default="upload your cirriculum")
    diploma = models.FileField(upload_to= 'diploma/',verbose_name="Diploma", default="upload your diploma")
    Retus = models.FileField(upload_to= 'Retus/',verbose_name="Retus", default = "upload your retus")
    courses = models.FileField(upload_to= 'courses/',verbose_name="Cursos", default="upload your courses")
    degree_certificate = models.FileField(upload_to= 'degree_certificate/',verbose_name="Acta de grado", default="upload your degree certificate")
    title = models.FileField(upload_to= 'title/',verbose_name="Convalidacion titulo icfes", default="upload your title")
    #Contract
    contract = models.FileField(upload_to= 'contract/',verbose_name="Contrato", default="upload your contract")
    type_vinculation = models.CharField(max_length=100, verbose_name="Tipo de vinculacion", null=True)
    policy = models.FileField(upload_to= 'policy/',verbose_name="Poliza", default="upload your poliza")
    tariff = models.IntegerField(null=True, verbose_name="Tarifa")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edicion")
    Headquarters = models.ManyToManyField(Headquarters, verbose_name="Sede")

    @property
    def age(self):
        today = date.today()
        return today.year - self.birthday.year - ((today.month, today.day) < (self.birthday.month, self.birthday.day))

    # @property
    # def state(self):
    #     state = null
    #     if (active == True):
    #         state = "Activo"
    #     else:
    #         state = "Inactivo"
    #     return state

    class Meta:
        verbose_name = "Funcionario"
        verbose_name_plural = "Funcionarios"
        ordering = ["-created"]

    def __str__(self):
        return self.name

EmcoCrud/core/forms.py
from django import forms
from core.models import Funtionary, Headquarters
from django.contrib.auth.forms import  UserCreationForm
from django.contrib.auth.models import User


class FuntionaryForm(forms.ModelForm):
    class Meta:
        model = Funtionary
        fields = ("identification", "name", "lastname", "birthday", "telephone", "email", "active"
        , "speciality", "curriculum", "diploma", "Retus", "courses", "degree_certificate", "title", "contract"
        , "type_vinculation", "policy", "tariff", "Headquarters")



class CustomUserCreationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
	def clean_email(self):
		email = self.cleaned_data['email']

		if User.objects.filter(email=email).exists():
			raise forms.ValidationError('Este correo electrónico ya está registrado')
		return email

EmcoCrud/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Funtionary, Speciality, Headquarters
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from openpyxl import Workbook
from openpyxl.styles import *
import decimal
from  django import forms
from .forms import FuntionaryForm
from django.views.generic import CreateView
from django.views.generic import TemplateView
from django.db.models import Q
from django.utils.timezone import localtime
import pandas as pd
from django.db.models import F
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .forms import CustomUserCreationForm
from django.contrib.auth import authenticate, login

def index(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        return redirect('login')

# # Create your views here.
# def home(request):
#     return render(request, 'core/home.html')

def search(request):
    if 'q' in request.GET:
        q = request.GET['q']
        multiple_query =  Q(Q(name__icontains=q) | Q(lastname__icontains=q))
        funtionary_query = Funtionary.objects.filter(multiple_query)
    else:
        funtionary_query = Funtionary.objects.all()
    context = {
        'funtionary_query' : funtionary_query
    }
    return render(request, "core/search.html", context)

# def filter_query(request):
#     funtionary_ = Funtionary.objects.all()
#     speciality_filter = Speciality.objects.all()
#     headquarters_filter = Headquarters.objects.all()
#     filter_speciality = request.GET.get('filter-speciality')
#     filter_headquarter = request.GET.get('filter-headquarter')

#     if is_valid_queryparam(filter_headquarter) and filter_headquarter != 'Choose...':
#         funtionary_ = funtionary_.filter(headquarters_filter__nameHeadquarter=filter_headquarter)

#     if is_valid_queryparam(filter_speciality) and filter_speciality != 'Choose...':
#         funtionary_ = funtionary_.filter(speciality_filter__title=filter_speciality)

#     context = {
#         'funtionary_query' : funtionary_query,
#         'speciality_filter' : speciality_filter,
#         'headquarters_filter' : headquarters_filter,
#     }
#     return render(request, "core/search.html", context)

def home(request):
    funtionary_ = Funtionary.objects.all()
    return render(request, "core/home.html", {"funtionary_" : funtionary_})

def about(request):
    return render(request, "core/about.html")

def upload_funtionary(request):
    if request.method == 'POST':
        form = FuntionaryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = FuntionaryForm()
    context = {
        'form': form,
    }
    return render(request, 'core/add_data.html', context)


def deleteData(request,id):
    funtionary_ = Funtionary.objects.get(id=id)
    funtionary_.delete()
    return redirect('home')


def update_info(request, id):
    funtionary_ = get_object_or_404(Funtionary, id=id)
    if request.method == 'POST':
        form = FuntionaryForm(request.POST, request.FILES, instance=funtionary_)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = FuntionaryForm(instance=funtionary_)
    return render(request, 'core/update_info.html', {'form': form})

def export_to_excel(request):
    # Obtener los datos de los funcionarios con los campos necesarios
    funcionarios = Funtionary.objects.all()

    # Lista de campos que deseas exportar
    campos_exportar = [
        'identification', 'name', 'lastname', 'birthday', 'telephone', 'email', 'active',
        'speciality__title'
    ]

    # Obtener los datos y renombrar el campo especialidad
    datos = funcionarios.values(
        *campos_exportar
    ).annotate(
        headquarters_list=F('Headquarters__nameHeadquarter')
    )

    # Crear el DataFrame de pandas
    df = pd.DataFrame(datos)

    # Renombrar la columna 'speciality__title' a 'speciality' si es necesario
    df.rename(columns={'speciality__title': 'speciality__title'}, inplace=True)

    # Asegurarse de que las fechas estén en el formato correcto sin zona horaria
    df['birthday'] = pd.to_datetime(df['birthday']).dt.tz_localize(None)

    # Agrupar todas las filas por los campos especificados en campos_exportar
    df_final = df.groupby(campos_exportar).agg({
        'headquarters_list': ', '.join
    }).reset_index()

    # Diccionario para renombrar las columnas al español
    columnas_esp = {
        'identification': 'Identificación',
        'name': 'Nombre',
        'lastname': 'Apellido',
        'birthday': 'Fecha de Nacimiento',
        'telephone': 'Teléfono',
        'email': 'Correo Electrónico',
        'active': 'Activo',
        'speciality': 'Especialidad',
        'headquarters_list': 'Lista de Sedes'
    }

    # Renombrar las columnas en el DataFrame
    df_final.rename(columns=columnas_esp, inplace=True)

    # Crear un objeto HttpResponse con el tipo de contenido adecuado
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=funcionarios.xlsx'

    # Utilizar pandas para escribir los datos a un archivo de Excel en el response
    with pd.ExcelWriter(response, engine='openpyxl') as writer:
        df_final.to_excel(writer, index=False, sheet_name='Funcionarios')

    return response

@login_required
def products(request):
    return render(request, 'core/products.html')

def register(request):
    data = {
        'form': CustomUserCreationForm()
    }

    if request.method == 'POST':
        user_creation_form = CustomUserCreationForm(data=request.POST)

        if user_creation_form.is_valid():
            user_creation_form.save()

            user = authenticate(username=user_creation_form.cleaned_data['username'], password=user_creation_form.cleaned_data['password1'])
            login(request, user)
            return redirect('login')
        else:
            data['form'] = user_creation_form

    return render(request, 'registration/register.html', data)

EmcoCrud/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}Acerca{% endblock %}

{% block content %}

<h2>Acerca de </h2>
<p>Esta una plataforma realizada durante las practicas</p>
{% endblock %}

EmcoCrud/core/templates/core/add_data.html
{% extends 'core/base.html' %}

{% block title %}Edicion de registros{% endblock %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Ingreso de registros</h2>
<p>Bienvenido al apartado de ingreso de datos</p>

    <div class="capa">
        <main role="main">
            <div class="container">
                <div class="row mt-3">
                    <div class="col-md-9 mx-auto mb-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <h2>Registro de datos</h2>
                            {{form|crispy}}
                            <input class="btn btn-primary" type="submit" value="Subir">
                        </form>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

{% block scripts %}

    <script>
        $("#id_Headquarters").select2();
    </script>

{% endblock %}

EmcoCrud/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Emco Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body>
    <h1>EmcoCrud</h1>

    <ul class="nav nav-underline">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="nav-link btn btn-link">Salir</button>
                </form>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Ingresar</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
            </li>
        {% endif %}
    </ul>

    {% block content %}
    
    {% endblock %}

    {% block scripts %}
    
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Aplicación</title>
    
</head>
<body>

    
</body>
</html>

EmcoCrud/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
{% load static %}

    <!--Filters
  <nav class="navbar bg-body-tertiary">
    <div class="container-fluid">
      <form method="get" class="d-flex">
        <select class="form-select" aria-label="Default select example" id="filter-speciality" name="filter-speciality">
          <option selected>Selecciona la Especialidad</option>
          {% for f in speciality_filter %}
            <option value="{{f}}">{{f}}</option>
          {% endfor%}
        </select>
    
        <select class="form-select" aria-label="Default select example" id="filter-headquarter" name="filter-headquarter">
          <option selected>Selecciona la Sede</option>
          {% for f in headquarters_filter %}
            <option value="{{f}}">{{f}}</option>
          {% endfor%}
        </select>
      </form>
    </div>

    <div class="container-fluid">
      <form class="d-flex" role="search" action="{% url 'search' %}">
        <input class="form-control me-2" name="q" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-info" type="submit">Buscar</button>
      </form>
    </div>
  </nav>-->

    <h3>Inicio</h3>
    {% if request.user.is_authenticated %}
        <hr>
        <h4>
            {{ user.username | upper }}, bienvenido
        </h4>
    {% endif %}

  <!--Modal to delete confirmation-->
  <div class="modal" tabindex="-1" id="deleteModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Confirmar eliminacion</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>¿Estas seguro de querer eliminar este registro?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="#" id="confirmDeleteBtn">Si, definitivamente</a>
        </div>
      </div>
    </div>
  </div>


    <table class="table">
    <tbody>
        <thead>
            <tr>
            <th scope="col">ID</th>
            <th scope="col">Identificacion</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Edad</th>
            <th scope="col">Telefono</th>
            <th scope="col">Email</th>
            <th scope="col">Estado</th>
            <th scope="col">Especialidad</th>
            <th scope="col">Sede</th>
            <th scope="col">Contrato</th>
            <th colspan="2">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for f in funtionary_ %}
            <tr>
                <th scope="row">{{f.id}}</th>
                <td>{{f.identification}}</td>
                <td>{{f.name}}</td>
                <td>{{f.lastname}}</td>
                <td>{{f.age}}</td>
                <td>{{f.telephone}}</td>
                <td>{{f.email}}</td>
                <td>{% if f.active %}Activo{% else %}Inactivo{% endif %}</td>
                <td>{{f.speciality}}</td>
                <td>
                    {% for headquarters in f.Headquarters.all %}
                    {{ headquarters.nameHeadquarter }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
                <td>
                    <a href="{{ f.contract.url }}" target="_blank">Ver</a>
                </td>
                <td><a href="update_info/{{f.id}}"class="btn btn-warning">Editar</a></td>
                <td><a href="deleteData/{{f.id}}" class="btn btn-danger delete-btn">Eliminar</a></td>

            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <th><a class="btn btn-success" href="{% url 'upload_funtionary' %}">Agregar</a></th>
            <th><a href="{% url 'export_to_excel' %}" class="btn btn-primary">Exportar</button></th>   
        </tfoot>
    </tbody>
    </table>

  <script>
    $(document).ready(function(){
        $('.delete-btn').on('click', function(e){
            e.preventDefault();
            var url = $(this).attr('href');
            $('#confirmDeleteBtn').attr('href', url);
            $('#deleteModal').modal('show');
        });
    });
  </script>


{% endblock %}

EmcoCrud/core/templates/core/products.html
{% extends 'core/base.html' %}

{% block content %}

<h3>Productos</h3>

<p>Producto 1</p>
<p>Producto 2</p>
<p>Producto 3</p>
<p>Producto 4</p>
<p>Producto 5</p>
<p>Producto 6</p>


{% endblock %}

EmcoCrud/core/templates/core/search.html
{% extends 'core/base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
{% load static %}


<!--Modal to delete confirmation-->
  <div class="modal" tabindex="-1" id="deleteModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Confirmar eliminacion</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>¿Estas seguro de querer eliminar este registro?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="#" id="confirmDeleteBtn">Si, definitivamente</a>
        </div>
      </div>
    </div>
  </div>

  <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Identificacion</th>
          <th scope="col">Nombre</th>
          <th scope="col">Apellido</th>
          <th scope="col">Edad</th>
          <th scope="col">Telefono</th>
          <th scope="col">Email</th>
          <th scope="col">Estado</th>
          <th scope="col">Especialidad</th>
          <th scope="col">Sede</th>
          <th scope="col">Contrato</th>
          <th colspan="2">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for f in funtionary_query %}
          <tr>
              <th scope="row">{{f.id}}</th>
              <td>{{f.identification}}</td>
              <td>{{f.name}}</td>
              <td>{{f.lastname}}</td>
              <td>{{f.age}}</td>
              <td>{{f.telephone}}</td>
              <td>{{f.email}}</td>
              <td>{% if f.active %}Activo{% else %}Inactivo{% endif %}</td>
              <td>{{f.speciality}}</td>
              <td>
                {% for headquarters in f.Headquarters.all %}
                  {{ headquarters.nameHeadquarter }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
              </td>
              <td>
                <a href="{{ f.contract.url }}" target="_blank">Ver</a>
              </td>
              <td><a href="update_info/{{f.id}}"class="btn btn-warning">Editar</a></td>
              <td><a href="deleteData/{{f.id}}" class="btn btn-danger delete-btn">Eliminar</a></td>

          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
          <th><a class="btn btn-success" href="{% url 'upload_funtionary' %}">Agregar</a></th>
          <th><button type="button" class="btn btn-primary">Exportar</button></th>
      </tfoot>
  </table>

  <script>
    $(document).ready(function(){
        $('.delete-btn').on('click', function(e){
            e.preventDefault();
            var url = $(this).attr('href');
            $('#confirmDeleteBtn').attr('href', url);
            $('#deleteModal').modal('show');
        });
    });
  </script>


{% endblock %}

EmcoCrud/core/templates/core/update_info.html
{% extends 'core/base.html' %}

{% block title %}Edicion de registros{% endblock %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Ingreso de registros</h2>
<p>Bienvenido al apartado de edicion de datos</p>

    <div class="capa">
        <main role="main">
            <div class="container">
                <div class="row mt-3">
                    <div class="col-md-9 mx-auto mb-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <h2>Edicion de datos</h2>
                            {{form|crispy}}
                            <input class="btn btn-primary" type="submit" value="Editar">
                        </form>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

{% block scripts %}

    <script>
        $("#id_Headquarters").select2();
    </script>

{% endblock %}